type: object
additionalProperties: false
properties:
  tables:
    description: >
      List of the tables required by your Sky deployment.  These are created if they do not already exist.  Tables are created with the DeletionPolicy, Retain.  So, when your deployment is deleted by Sky, that operation is non-destructive to your data.
    type: array
    uniqueItems: true
    items:
      type: object
      additionalProperties: false
      required: [name, keySchema, attributeDefinitions, provisionedThroughput]
      properties:
        name: {$ref: "#/definitions/name"}
        keySchema: {$ref: "#/definitions/keySchema"}
        attributeDefinitions: {$ref: "#/definitions/attributeDefinitions"}
        provisionedThroughput: {$ref: "#/definitions/provisionedThroughput"}
        globalSecondaryIndex:
          type: object
          additionalProperties: false
          required: [name, keySchema, projection, provisionedThroughput]
          properties:
            name: {$ref: "#/definitions/name"}
            keySchema: {$ref: "#/definitions/keySchema"}
            projection: {$ref: "#/definitions/projection"}
            provisionedThroughput: {$ref: "#/definitions/provisionedThroughput"}
        localSecondaryIndex:
          type: object
          additionalProperties: false
          required: [name, keySchema, projection]
          properties:
            name: {$ref: "#/definitions/name"}
            keySchema: {$ref: "#/definitions/keySchema"}
            projection: {$ref: "#/definitions/projection"}


  tags:
    description: >
      Optional tags attached to your tables to make it easier to track and monitor. These tags are applied in addition to the ones that are part of
      the global Sky configuration, so there is no need to repeat.
    type: array
    minItems: 1
    uniqueItems: true
    items:
      type: object
      additionalProperties: false
      required: [ Key, Value ]
      properties:
        Key:
          description: >
            Name of tag. This is an arbitrary string you provide to track
            resource groupings of interest.
          type: string
        Value:
          description: >
            The value that goes with the matching tag type. This is an
            aribitrary string you provide to track resource groupings of
            interest.
          type: string
